require:
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'spec/fixtures/**/*'
    - 'tmp/**/*'
    - 'front-end/**/*'
    - 'spec/smoke_tests/**/*.rb'
    - 'bin/**/*'
    - 'db/schema.rb'

Style/Documentation:
  Enabled: false
Style/HashSyntax:
  EnforcedShorthandSyntax: either

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/environments/*"
Metrics/MethodLength:
  Exclude:
    - "spec/**/*"
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/EmptyExampleGroup:
  Exclude:
    - "spec/requests/**/*"
